import{S as p,i as l,b as m}from"./assets/vendor-7aac2d1c.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const c of e.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function o(t){if(t.ep)return;t.ep=!0;const e=s(t);fetch(t.href,e)}})();const a={formSearch:document.getElementById("formSearch"),inputSearch:document.getElementById("inputSearch"),btnSearch:document.getElementById("btnSearch"),galleryList:document.querySelector(".js-ImagesCart"),loader:document.querySelector(".loader")};a.formSearch.addEventListener("submit",h);a.galleryList.addEventListener("click",b);const y=new p(".js-ImagesCart a",{captionsData:"alt",captionDelay:250});function h(r){r.preventDefault();const n="https://pixabay.com/api/",s="43910002-4f8293575df59775d1c0606c1",o=a.inputSearch.value.trim(),t=new URLSearchParams({key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",lang:"en"});return a.loader.style.display="block",fetch(`${n}?${t}`).then(e=>{if(!e.ok)throw new Error(e.statusText);return e.json()}).then(e=>{if(e.hits.length===0){l.show({message:"Sorry, there are no images matching your search query. Please, try again!",timeout:5e3,backgroundColor:"#EF4040"});return}a.galleryList.innerHTML=S(e.hits),y.refresh()}).catch(e=>{console.log(e),l.show({message:"Something went wrong. Please, try again later.",timeout:5e3,backgroundColor:"#EF4040"})}).finally(()=>{a.loader.style.display="none"})}function S(r){return r.map(({webformatURL:n,largeImageURL:s,tags:o,likes:t,views:e,comments:c,downloads:g})=>`
          <li class="js-list">
              <a href="${s}"><img class="js-image" src="${n}" alt="${o}" /></a>
              <ul class="js-dates">
                  <li class="js-likes">Likes: ${t}</li>
                  <li class="js-views">Views: ${e}</li>
                  <li class="js-comments">Comments: ${c}</li>
                  <li class="js-downloads">Downloads: ${g}</li>
              </ul>
          </li>
      `).join("")}function b(r){if(r.preventDefault(),r.target.nodeName!=="IMG")return;const n=r.target.closest("a").href;m.create(`<img src="${n}" width="800" height="600" alt="${r.target.alt}">`,{onShow:()=>{document.addEventListener("keydown",d)},onClose:()=>{document.removeEventListener("keydown",d)}})}function d(r){if(r.code==="Escape"){const n=m.visible();n&&n.close()}}const i={formSearch:document.getElementById("formSearch"),inputSearch:document.getElementById("inputSearch"),btnSearch:document.getElementById("btnSearch"),galleryList:document.querySelector(".js-ImagesCart"),loader:document.querySelector(".loader")};function E(r){r.preventDefault(),f()}function f(){i.inputSearch.value.trim()===""?(l.show({message:"please,enter the name of the picture you are looking fo for",timeout:5e3,backgroundColor:"#a0cdde"}),i.btnSearch.disabled=!0):i.btnSearch.disabled=!1}const u={formSearch:document.getElementById("formSearch"),inputSearch:document.getElementById("inputSearch"),btnSearch:document.getElementById("btnSearch"),galleryList:document.querySelector(".js-ImagesCart"),loader:document.querySelector(".loader")};u.formSearch.addEventListener("submit",E);u.inputSearch.addEventListener("input",f);u.btnSearch.addEventListener("click",h);
//# sourceMappingURL=commonHelpers.js.map
