import{i as l,S as f}from"./assets/vendor-0fc460d7.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const c of e.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function a(t){if(t.ep)return;t.ep=!0;const e=s(t);fetch(t.href,e)}})();const i={formSearch:document.getElementById("formSearch"),inputSearch:document.getElementById("inputSearch"),btnSearch:document.getElementById("btnSearch"),galleryList:document.querySelector(".js-ImagesCart"),loader:document.querySelector(".loader")};function d(){const o=i.inputSearch.value.trim(),n=i.inputSearch.placeholder;return o===""||o===n?(l.show({message:"Please, enter the name of the picture you are looking for",timeout:5e3,backgroundColor:"#a0cdde"}),i.btnSearch.disabled=!0,!1):(i.btnSearch.disabled=!1,!0)}const r={formSearch:document.getElementById("formSearch"),inputSearch:document.getElementById("inputSearch"),btnSearch:document.getElementById("btnSearch"),galleryList:document.querySelector(".js-ImagesCart"),loader:document.querySelector(".loader")};r.formSearch.addEventListener("submit",m);const p=new f(".js-ImagesCart a",{captionsData:"alt",captionDelay:250});function m(o){if(o.preventDefault(),!d())return;r.galleryList.innerHTML="";const n="https://pixabay.com/api/",s="43910002-4f8293575df59775d1c0606c1",a=r.inputSearch.value.trim(),t=new URLSearchParams({key:s,q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",lang:"en"});r.loader.style.display="block",fetch(`${n}?${t}`).then(e=>{if(!e.ok)throw new Error(e.statusText);return e.json()}).then(e=>{if(e.hits.length===0){l.show({message:"Sorry, there are no images matching your search query. Please, try again!",timeout:5e3,backgroundColor:"#EF4040"});return}r.galleryList.innerHTML=g(e.hits),p.refresh()}).catch(e=>{console.log(e),l.show({message:"Something went wrong. Please, try again later.",timeout:5e3,backgroundColor:"#EF4040"})}).finally(()=>{r.loader.style.display="none"})}function g(o){return o.map(({webformatURL:n,largeImageURL:s,tags:a,likes:t,views:e,comments:c,downloads:h})=>`
          <li class="js-list">
              <a href="${s}"><img class="js-image" src="${n}" alt="${a}" /></a>
              <ul class="js-dates">
                  <li class="js-likes">Likes: ${t}</li>
                  <li class="js-views">Views: ${e}</li>
                  <li class="js-comments">Comments: ${c}</li>
                  <li class="js-downloads">Downloads: ${h}</li>
              </ul>
          </li>
      `).join("")}r.inputSearch.addEventListener("focus",()=>{r.inputSearch.placeholder=""});r.inputSearch.addEventListener("blur",()=>{r.inputSearch.value.trim()===""&&(r.inputSearch.placeholder="Please enter something")});const u={formSearch:document.getElementById("formSearch"),inputSearch:document.getElementById("inputSearch"),btnSearch:document.getElementById("btnSearch"),galleryList:document.querySelector(".js-ImagesCart"),loader:document.querySelector(".loader")};u.formSearch.addEventListener("submit",void 0);u.inputSearch.addEventListener("input",d);u.btnSearch.addEventListener("click",m);
//# sourceMappingURL=commonHelpers.js.map
